[package]
name = "hulk_ros_z"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[package.metadata.pepsi]
cross-compile = true

[dependencies]
booster.workspace = true
booster_sdk.workspace = true
cdr.workspace = true
clap = { workspace = true, features = ["derive"] }
color-eyre = { workspace = true }
coordinate_systems = { workspace = true }
futures-util.workspace = true
geometry = { workspace = true }
image = { workspace = true }
kinematics = { workspace = true }
linear_algebra = { workspace = true }
log.workspace = true
ndarray = { workspace = true }
ort = { workspace = true, features = ["cuda", "tensorrt", "load-dynamic"] }
ros-z = { workspace = true }
ros-z-config = { workspace = true }
ros-z-msgs = { workspace = true, features = ["sensor_msgs"] }
ros2.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
types = { workspace = true }
zenoh = { workspace = true }
projection = {workspace = true}
