[package]
name = "baldrian"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
futures-util = { workspace = true }
hyper = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
